# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 Keysight Technologies Inc, or its subsidiaries.
from ..proto.network import networktypes_pb2
from ..proto.network import networktypes_pb2_grpc
from ..proto.network import openconfig_interfaces_pb2
from ..proto.network import openconfig_interfaces_pb2_grpc
from ..proto.network import vpc_pb2_grpc
from ..proto.network import networkpolicy_pb2
from ..proto.network import vnic_pb2_grpc
from ..proto.network import port_pb2_grpc
from ..proto.network import port_pb2
from ..proto.network import device_pb2
from ..proto.network import tunnel_pb2
from ..proto.network import bgp_pb2
from ..proto.network import interface_pb2
from ..proto.network import device_pb2_grpc
from ..proto.network import tunnel_pb2_grpc
from ..proto.network import vnic_pb2
from ..proto.network import route_pb2_grpc
from ..proto.network import underlayroute_pb2_grpc
from ..proto.network import cloudrpc_pb2_grpc
from ..proto.network import networkpolicy_pb2_grpc
from ..proto.network import vpc_pb2
from ..proto.network import mapping_pb2
from ..proto.network import bgp_pb2_grpc
from ..proto.network import underlayroute_pb2
from ..proto.network import cloudrpc_pb2
from ..proto.network import route_pb2
from ..proto.network import subnet_pb2_grpc
from ..proto.network import mapping_pb2_grpc
from ..proto.network import interface_pb2_grpc
from ..proto.network import nexthop_pb2
from ..proto.network import subnet_pb2
from ..proto.network import nexthop_pb2_grpc
from ..proto.network import l3_xpu_infra_mgr_pb2
from ..proto.network import l2_xpu_infra_mgr_pb2_grpc
from ..proto.network import l2_xpu_infra_mgr_pb2
from ..proto.network import l3_xpu_infra_mgr_pb2_grpc
from ..proto.network import telco_pb2
from ..proto.network import telco_pb2_grpc
from ..proto.network import k8s_pb2_grpc
from ..proto.network import k8s_pb2
